from .noise import generate_tk95_noise

import numpy as np

# Default to 10 ns (100 MHz sampling) to capture high-frequency phase jitters up to 50MHz (Nyquist sampling theorem)
DEFAULT_DT = 1e-8  
# Default to 100,000 samples (~1 ms of total time) 
DEFAULT_N_SAMPLES = 100_000

class PhaseNoiseSimulator:
    """
    High-level orchestrator class for generating laser noise trajectories.

    This class handles the interpolation of experimental PSD data onto a 
    linear frequency grid and manages the execution of the TK95 algorithm.

    The generateNoise() method returns a unique time-domain phase noise
    trajectory in units of radians.

    The interpolated frequency grid (f_linear_full, psd_linear_full) is
    pre-computed at construction time and is immediately available as
    instance attributes without needing to call generateNoise() first.
    If generateNoise() is called with dt or n_samples overrides, the grid
    is recomputed on the fly for that call only — the default grid is
    preserved on the instance.

    Reproducible trajectories can be generated by passing seed=<int>
    to __init__, which fixes the internal numpy.random.Generator state.

    NOTE: Method is agnostic about the units/dataType of PSD.
    (Phase, Voltage, frequency PSD return their corresponding noise arrays.)
    """

    def __init__(self, frequencies, psd, dt=DEFAULT_DT, n_samples=DEFAULT_N_SAMPLES,
                 extrapolation_mode='floor', beta=2.0, zero_offset=True, seed=None):
        """
        Parameters
        ----------
        frequencies : array_like
            Input frequency axis (Hz) from experimental data.
        psd : array_like
            Input Power Spectral Density (rad^2/Hz).
        dt : float
            Desired time step for the output trajectory (seconds).
        n_samples : int
            Total number of samples to generate in the time domain.
        extrapolation_mode : str
            Keyword for handling frequencies outside of data range:
            'zero', 'floor', or 'decay' (Kohlrausch).
        beta : float
            Decay exponent (Kohlrausch) if extrapolation_mode='decay'.
            Preset to 2.0 for 1/f^2 decay.
        zero_offset : bool
            If True, shifts the trajectory so phi[0] = 0. Default is True.
        seed : int or None
            Seed for the random number generator. None (default) gives a
            different trajectory on each run. An integer gives fully
            reproducible output — successive generateNoise() calls on the
            same simulator return different but reproducible trajectories
            as the RNG state advances. To recreate the exact same sequence,
            re-instantiate the simulator with the same seed.
        """

        if len(frequencies) != len(psd):
            raise ValueError("Frequencies and PSD arrays must have the same length.")

        self.frequencies = np.asarray(frequencies)
        self.psd         = np.asarray(psd)
        self.dt          = dt
        self.n_samples   = n_samples

        self.extrapolation_mode = extrapolation_mode.lower()
        self.beta        = beta
        self.zero_offset = zero_offset

        self.fs_nyq = 1 / (2 * dt)
        self.df     = 1 / (dt * n_samples)

        # Initialise RNG — seeded for reproducibility, or random if seed=None
        self.seed = seed
        self.rng  = np.random.default_rng(seed)

        self._get_linear_grid(self.n_samples, self.dt)

    def _interpolate_log_psd(self, f_target):
        """
        Maps the experimental PSD to target frequencies using log-log
        interpolation and the specified extrapolation mode.

        Parameters
        ----------
        f_target : ndarray
            Array of positive frequencies (excluding DC) onto which the
            experimental PSD is interpolated.
        """
        log_f_target = np.log(f_target)
        log_f_data   = np.log(self.frequencies)
        log_psd_data = np.log(self.psd)

        # Set boundary values for np.interp based on extrapolation mode
        if self.extrapolation_mode == 'zero':
            l_val, r_val = -np.inf, -np.inf
        elif self.extrapolation_mode == 'decay':
            l_val, r_val = log_psd_data[0], -np.inf   # Decay handled manually below
        else:
            l_val, r_val = log_psd_data[0], log_psd_data[-1]

        log_psd_interp = np.interp(
            log_f_target, log_f_data, log_psd_data,
            left=l_val, right=r_val
        )

        # Apply Kohlrausch/power-law decay on the high-frequency side
        if self.extrapolation_mode == 'decay':
            high_freq_mask = f_target > self.frequencies[-1]
            log_f_last     = log_f_data[-1]
            log_psd_last   = log_psd_data[-1]

            log_psd_interp[high_freq_mask] = log_psd_last - self.beta * (
                log_f_target[high_freq_mask] - log_f_last
            )

        return np.exp(log_psd_interp)

    def _get_linear_grid(self, n_samples, dt):
        """
        Interpolates the input PSD onto a linear grid spanning [-f_Nyq, f_Nyq]
        and stores the result as instance attributes f_linear_full and
        psd_linear_full.

        Parameters
        ----------
        n_samples : int
            Number of samples for this grid computation.
        dt : float
            Time step for this grid computation.

        Returns
        -------
        f_linear_full : ndarray
        psd_linear_full : ndarray
        """
        fs_nyq = 1 / (2 * dt)
        df     = 1 / (dt * n_samples)

        # Create linear positive frequency axis (excluding DC)
        f_linear_pos = np.arange(df, fs_nyq, df)
        psd_interp   = self._interpolate_log_psd(f_linear_pos)

        # Prepend DC bin (set to 0)
        psd_linear_pos       = np.insert(psd_interp, 0, 0)
        f_linear_pos_with_dc = np.insert(f_linear_pos, 0, 0)

        # Construct full symmetric frequency axis for TK95
        # fs = [0, df, ..., f_nyq, -f_nyq+df, ..., -df]
        f_linear_full   = np.fft.fftfreq(n_samples, d=dt)
        psd_linear_full = np.interp(
            np.abs(f_linear_full), f_linear_pos_with_dc, psd_linear_pos
        )

        self.f_linear_full   = f_linear_full
        self.psd_linear_full = psd_linear_full

        return f_linear_full, psd_linear_full

    def generateNoise(self, n_samples=None, dt=None):
        """
        Generates a time-domain noise trajectory using the TK95 algorithm.

        If n_samples or dt overrides are passed, the interpolated grid is
        recomputed for that call only — the default grid stored on the
        instance (f_linear_full, psd_linear_full) is not modified.

        Parameters
        ----------
        n_samples : int, optional
            Number of points to generate. Defaults to self.n_samples.
        dt : float, optional
            Time step in seconds. Defaults to self.dt.

        Returns
        -------
        t : ndarray
            Time axis (seconds).
        phi : ndarray
            Noise trajectory (radians).
        """
        N     = n_samples if n_samples is not None else self.n_samples
        tstep = dt        if dt        is not None else self.dt

        if n_samples is not None or dt is not None:
            fs, psd_mapped = self._get_linear_grid(N, tstep)
            self._get_linear_grid(self.n_samples, self.dt)
        else:
            fs, psd_mapped = self.f_linear_full, self.psd_linear_full

        t   = np.arange(N) * tstep
        phi = generate_tk95_noise(fs, psd_mapped, self.rng)

        if self.zero_offset:
            phi -= phi[0]

        return t, phi


def phasenoise_maker(frequencies, psd, dt=1e-6, n_samples=1000, **kwargs):
    """
    Functional wrapper for quick noise generation.
    """
    sim = PhaseNoiseSimulator(frequencies, psd, dt=dt, n_samples=n_samples, **kwargs)
    return sim.generateNoise()
