from .noise import generate_tk95_noise

import numpy as np

# Default to 10 ns (100 MHz sampling) to capture high-frequency phase jitters up to 50MHz (Nyquist sampling theorem)
DEFAULT_DT = 1e-8  
# Default to 100,000 samples (~1 ms of total time) 
DEFAULT_N_SAMPLES = 100_000

class PhaseNoiseSimulator:
    """
    High-level orchestrator class for generating laser noise trajectories.

    This class handles the interpolation of experimental PSD data onto a 
    linear frequency grid and manages the execution of the TK95 algorithm.

    The generateNoise() method returns a unique time-domain phase noise
    trajectory in units of radians.

    The interpolated one-sided frequency grid (f_linear, psd_linear) is
    pre-computed at construction time at the default n_samples resolution
    and is immediately available as instance attributes. These are strictly
    one-sided (DC + positive frequencies only), so the expected variance
    of a generated trajectory is recovered directly as:

        np.sum(sim.psd_linear) * sim.df

    Internally, generateNoise() operates on a doubled grid to implement
    double-and-discard (see generateNoise docstring). This does not affect
    the user-facing attributes.

    Reproducible trajectories can be generated by passing seed=<int>
    to __init__, which fixes the internal numpy.random.Generator state.

    NOTE: Method is agnostic about the units/dataType of PSD.
    (Phase, Voltage, frequency PSD return their corresponding noise arrays.)
    """

    def __init__(self, frequencies, psd, dt=DEFAULT_DT, n_samples=DEFAULT_N_SAMPLES,
                 extrapolation_mode='floor', beta=2.0, zero_offset=True, seed=None):
        """
        Parameters
        ----------
        frequencies : array_like
            Input frequency axis (Hz) from experimental data.
        psd : array_like
            Input Power Spectral Density (rad^2/Hz).
        dt : float
            Desired time step for the output trajectory (seconds).
        n_samples : int
            Total number of samples to generate in the time domain.
        extrapolation_mode : str
            Keyword for handling frequencies outside of data range:
            'zero', 'floor', or 'decay' (Kohlrausch).
        beta : float
            Decay exponent (Kohlrausch) if extrapolation_mode='decay'.
            Preset to 2.0 for 1/f^2 decay.
        zero_offset : bool
            If True, shifts the trajectory so phi[0] = 0. Default is True.
        seed : int or None
            Seed for the random number generator. None (default) gives a
            different trajectory on each run. An integer gives fully
            reproducible output — successive generateNoise() calls on the
            same simulator return different but reproducible trajectories
            as the RNG state advances. To recreate the exact same sequence,
            re-instantiate the simulator with the same seed.
        """

        if len(frequencies) != len(psd):
            raise ValueError("Frequencies and PSD arrays must have the same length.")

        self.frequencies = np.asarray(frequencies)
        self.psd         = np.asarray(psd)
        self.dt          = dt
        self.n_samples   = n_samples

        self.extrapolation_mode = extrapolation_mode.lower()
        self.beta        = beta
        self.zero_offset = zero_offset

        self.fs_nyq = 1 / (2 * dt)
        self.df     = 1 / (dt * n_samples)

        # Initialise RNG — seeded for reproducibility, or random if seed=None
        self.seed = seed
        self.rng  = np.random.default_rng(seed)

        # Pre-compute the one-sided interpolated grid at the default resolution.
        # These are the user-facing attributes: one-sided, DC at index 0.
        # Variance of a generated trajectory equals np.sum(psd_linear) * df exactly.
        self.f_linear, self.psd_linear = self._get_linear_grid(self.n_samples, self.dt)

    def _interpolate_log_psd(self, f_target):
        """
        Maps the experimental PSD to target frequencies using log-log
        interpolation and the specified extrapolation mode.

        Parameters
        ----------
        f_target : ndarray
            Array of positive frequencies (excluding DC) onto which the
            experimental PSD is interpolated.
        """
        log_f_target = np.log(f_target)
        log_f_data   = np.log(self.frequencies)
        log_psd_data = np.log(self.psd)

        # Set boundary values for np.interp based on extrapolation mode
        if self.extrapolation_mode == 'zero':
            l_val, r_val = -np.inf, -np.inf
        elif self.extrapolation_mode == 'decay':
            l_val, r_val = log_psd_data[0], -np.inf   # Decay handled manually below
        else:
            l_val, r_val = log_psd_data[0], log_psd_data[-1]

        log_psd_interp = np.interp(
            log_f_target, log_f_data, log_psd_data,
            left=l_val, right=r_val
        )

        # Apply Kohlrausch/power-law decay on the high-frequency side
        if self.extrapolation_mode == 'decay':
            high_freq_mask = f_target > self.frequencies[-1]
            log_f_last     = log_f_data[-1]
            log_psd_last   = log_psd_data[-1]

            log_psd_interp[high_freq_mask] = log_psd_last - self.beta * (
                log_f_target[high_freq_mask] - log_f_last
            )

        return np.exp(log_psd_interp)

    def _get_linear_grid(self, n_samples, dt):
        """
        Interpolates the input PSD onto a one-sided linear frequency grid
        spanning [0, f_Nyq) and returns the result.

        Pure function — does not write to any instance attributes.
        The caller decides whether to store the returned arrays.

        Parameters
        ----------
        n_samples : int
            Number of time-domain samples for this grid.
        dt : float
            Time step for this grid (seconds).

        Returns
        -------
        f_pos : ndarray
            One-sided frequency axis [0, df, ..., f_Nyq), length n_samples // 2.
        psd_pos : ndarray
            Interpolated one-sided PSD, same shape as f_pos.
        """
        df     = 1 / (dt * n_samples)
        fs_nyq = 1 / (2 * dt)

        f_pos      = np.arange(df, fs_nyq, df)
        psd_interp = self._interpolate_log_psd(f_pos)

        # Prepend DC bin — zero power enforces zero mean in the time domain
        f_pos   = np.concatenate(([0.0], f_pos))
        psd_pos = np.concatenate(([0.0], psd_interp))

        return f_pos, psd_pos

    def generateNoise(self, n_samples=None, dt=None):
        """
        Generates a time-domain noise trajectory using the TK95 algorithm.

        If n_samples or dt overrides are passed, a temporary grid is
        recomputed for that call only — the default grid stored on the
        instance (f_linear, psd_linear) is not modified.

        Parameters
        ----------
        n_samples : int, optional
            Number of points to generate. Defaults to self.n_samples.
        dt : float, optional
            Time step in seconds. Defaults to self.dt.

        Returns
        -------
        t : ndarray
            Time axis (seconds).
        phi : ndarray
            Noise trajectory (radians).
        """
        N     = n_samples if n_samples is not None else self.n_samples
        tstep = dt        if dt        is not None else self.dt

        # Double-and-discard: TK95 is based on an IFFT, which implicitly assumes
        # the signal is periodic over the window. This forces the trajectory to
        # wrap back toward its starting value in the second half of the array,
        # violating the non-Markovian diffusion expected of laser phase noise.
        # Generating 2*N samples and returning only the first N ensures the
        # wrap-back artefact is always discarded. FFT cost is O(N log N) so
        # the 2x overhead is negligible for typical signal lengths.
        N_internal  = 2 * N
        df_internal = 1.0 / (N_internal * tstep)

        _, psd_pos = self._get_linear_grid(N_internal, tstep)

        t   = np.arange(N) * tstep
        phi = generate_tk95_noise(df_internal, psd_pos, self.rng)[:N]

        if self.zero_offset:
            phi -= phi[0]

        return t, phi


def phasenoise_maker(frequencies, psd, dt=1e-6, n_samples=1000, **kwargs):
    """
    Functional wrapper for quick noise generation.
    """
    sim = PhaseNoiseSimulator(frequencies, psd, dt=dt, n_samples=n_samples, **kwargs)
    return sim.generateNoise()
